CPTS/CPTS/Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CPTS.Helpers;
using CPTS.Models;
using CPTS.Repository.Context;
using CPTS.Repository.Models;
using CPTS.Repository.Helpers;

namespace CPTS.Controllers
{
    [Authorize(Roles = "Read-Only User, Privileged User, Admin")]
    public class ActivityController : Controller
    {

        ActivityRepository activityRepository = new ActivityRepository();
        PartnerRepository partnerRepository = new PartnerRepository();
        CampusUnitRepository campusUnitRepository = new CampusUnitRepository();
        ContactRepository contactRepository = new ContactRepository();
        SafeURL URLHelper = new SafeURL();
        // GET: Activity
        public ActionResult Details(string id, DateTime date, string partnerName = "", string email = "")
        {
            var activity = activityRepository.FindActivityUsingSubjectContactDateAndPartner(id, date, URLHelper.CreateNameFromSafeName(partnerName), URLHelper.CreateEmailFromSafeEmail(email));
            activity.Partner = partnerRepository.GetPartnerByActivity(activity);
            activity.CampusUnit = campusUnitRepository.GetCampusUnitFromActivity(activity);
            activity.Contacts = contactRepository.FindContactsByActivity(activity);
            foreach (var contact in activity.Contacts) contact.URLSafeEmail = URLHelper.CreateURLSafeEmail(contact.Email);
            activity.ContactEmail = URLHelper.CreateURLSafeEmail(activity.Contacts.FirstOrDefault().Email);
            activity.URLSafeSubject = id;
            ViewBag.ContactCount = activity.Contacts.Count;

            return View(activity);
        }


        [Authorize(Roles = "Privileged User, Admin")]
        public ActionResult AddContacts(string id, string email)
        {
            var activity = activityRepository.FindSingleActivityFromSubject(id);
            activity.URLSafeSubject = id;
            var editActivity = new AddContactsActivity {Activity = activity};
            var partner = partnerRepository.GetPartnerByActivity(activity);
            editActivity.PartnerName = partner.PartnerName;
            editActivity.Activity.Partner = partner;
            editActivity.Contacts = contactRepository.ReturnAllContactsEmails();
            var contacts = contactRepository.FindContactsByActivity(activity);
            foreach (var contact in contacts)
            {
                editActivity.Contacts.Remove(contact.Email); // remove the Activity's Contacts from the list  
            }
            editActivity.ContactEmail = email;
            return View(editActivity);
        }

        [HttpPost]
        [Authorize(Roles = "Privileged User, Admin")]
        public ActionResult AddContacts(AddContactsActivity editActivity)
        {
            using (var context = new CPTSContext())
            {
                string subject = editActivity.Activity.URLSafeSubject.Replace(ConstantsChars.ReplacementCharForForwardSlash, '/');
                subject = subject.Replace(ConstantsChars.ReplacementCharForColon, ':');
                subject = subject.Replace(ConstantsChars.ReplacementCharForPeriod, '.');
                var updatedActivity = context.Activities.First(a => a.Subject == subject && a.Partner.PartnerName == editActivity.PartnerName && a.Date == editActivity.Activity.Date); // find the Activity
                updatedActivity.Partner = context.Partners.Find(editActivity.PartnerName); // find the Partner
                updatedActivity.Contacts = new List<Contact> { context.Contacts.Find(editActivity.ContactEmail) }; // create a list of Contacts with the new Contact
                updatedActivity.CampusUnit =
                    context.CampusUnits.First(c => c.Activities.Any(a => a.Subject == updatedActivity.Subject
                                                                         &&
                                                                         DbFunctions.TruncateTime(a.Date) ==
                                                                         DbFunctions.TruncateTime(updatedActivity.Date)
                                                                         &&
                                                                         a.Partner.PartnerName ==
                                                                         updatedActivity.Partner.PartnerName)); // find the CampusUnit
                var editContact = context.Contacts.Find(editActivity.ContactEmail); // find the new Contact to be added to the Activity
                context.Entry(editContact).State = EntityState.Modified; // Update the Contact
                context.SaveChanges();
                editActivity.ContactEmail = editActivity.ContactEmail.Replace('.', ConstantsChars.ReplacementCharForPeriod);
            }
            return RedirectToAction("Details", new { id = editActivity.Activity.URLSafeSubject, date = editActivity.Activity.Date, email = editActivity.ContactEmail });
        }


        [Authorize(Roles = "Privileged User, Admin")]
        public ActionResult ActivityEdit(string id, string email)
        {
            var activity = activityRepository.FindSingleActivityFromSubject(id);
            activity.Partner = partnerRepository.GetPartnerByActivity(activity);
            activity.CampusUnit = campusUnitRepository.GetCampusUnitFromActivity(activity);
            activity.Contacts = contactRepository.FindContactsByActivity(activity);
            activity.ContactEmail = email;
            activity.URLSafeSubject = id;

            if (activity.Notes == null)
            {
                activity.Notes = "";
            }

            return View(activity);
        }

        [HttpPost]
        [Authorize(Roles = "Privileged User, Admin")]
        public ActionResult ActivityEdit(Activity editActivity)//, string Subject)
        {
            editActivity.URLSafeSubject = editActivity.Subject.Replace('/', ConstantsChars.ReplacementCharForForwardSlash);     //Construct URL Safe Email
            editActivity.URLSafeSubject = editActivity.URLSafeSubject.Replace(':', ConstantsChars.ReplacementCharForColon);
            editActivity.URLSafeSubject = editActivity.URLSafeSubject.Replace('.', ConstantsChars.ReplacementCharForPeriod);

            editActivity.Date = activityRepository.GetDateByActivitySubject(editActivity.URLSafeSubject);
            editActivity.Partner = partnerRepository.GetPartnerByActivity(editActivity);
            editActivity.Partner = partnerRepository.GetSinglePartnerByName(editActivity.Partner.PartnerName);
            editActivity.CampusUnit = campusUnitRepository.GetCampusUnitFromActivity(editActivity);
            editActivity.Contacts = contactRepository.FindContactsByActivity(editActivity);

            //The hiccup comes when the validation is called and it doesn't appreciate the partner field
            //if (ModelState.IsValid)
            //{
                using (var context = new CPTSContext())
                {
                    context.Entry(editActivity).State = EntityState.Modified;
                    context.SaveChanges();
                }
                return RedirectToAction("Details", new { id = editActivity.Subject, date = editActivity.Date, email = editActivity.ContactEmail });
            //}
            //return View(editActivity);
        }
    }
}

CPTS/CPTS/Controllers/PartnerController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CPTS.Models;
using CPTS.Repository.Context;
using CPTS.Repository.Models;
using System.Text;
using CPTS.Repository.Helpers;
using CPTS.Helpers;

namespace CPTS.Controllers
{
    [Authorize(Roles = "Read-Only User, Privileged User, Admin")]
    public class PartnerController : Controller
    {
        ContactRepository contactRepository = new ContactRepository();
        PartnerRepository partnerRepository = new PartnerRepository();
        TagRepository tagRepository = new TagRepository();
        CampusUnitRepository campusUnitRepository = new CampusUnitRepository();
        ActivityRepository activityRepository = new ActivityRepository();
        SafeURL nameHelper = new SafeURL();

        // GET: Partner
        public ActionResult Details(string id, string search)
        {
            var partner = partnerRepository.GetSinglePartnerByName(id);
            partner.URLSafeName = id;
            var contacts = contactRepository.FindContactsFromPartnerName(partner.PartnerName);
            partner.SearchTags = tagRepository.FindTagsFromPartnerName(partner.PartnerName);
            partner.Contacts = contacts;
            partner.Activities = activityRepository.GetAllActivitiesForAPartner(partner.PartnerName);
            partner.tagString = "";

            for(int i = 0; i < partner.SearchTags.Count; i++)
            {
                partner.tagString += partner.SearchTags[i].TagName;
                if (i < partner.SearchTags.Count - 1) partner.tagString += ", ";
            }

            List<CampusUnit> campusUnits = campusUnitRepository.FindCampusUnitsForPartner(partner);
            for (int i = 0; i < campusUnits.Count; i++)
            {
                partner.campusUnitString += campusUnits[i].Name;
                if (i < campusUnits.Count - 1) partner.campusUnitString += ", ";
            }

            foreach (var partnerActivity in partner.Activities)
            {
                partnerActivity.Partner = partner;
                partnerActivity.CampusUnit = campusUnitRepository.GetCampusUnitFromActivityNonTruncateTime(partnerActivity);
                partnerActivity.URLSafeSubject = nameHelper.CreateUrlSafeSubject(partnerActivity.Subject);
            }

            if (search == null) partner.SearchString = "" + ConstantsChars.CharForStringSeperator + ConstantsChars.CharForStringSeperator + ConstantsChars.CharForStringSeperator;
            else partner.SearchString = search;
            ViewBag.Message = partner.Contacts.Count;

            return View(partner);
        }

        [Authorize(Roles = "Privileged User, Admin")]
        public ActionResult CreateContact(string id, string search)
        {
            var contact = new Contact();
            contact.Partner = partnerRepository.GetSinglePartnerByName(id);
            contact.Partner.SearchString = search;
            contact.Partner.URLSafeName = id;
            return View(contact);
        }

        [HttpPost]
        [Authorize(Roles = "Privileged User, Admin")]
        public ActionResult CreateContact(Contact newContact, string search)
        {
            newContact.Email = KeyTrimmer.TrimTrailingSpaces(newContact.Email);     //Trim white spaces off of contact email
            newContact.URLSafeEmail = KeyTrimmer.TrimTrailingSpaces(newContact.URLSafeEmail);
            newContact.Partner = partnerRepository.GetSinglePartnerByName(newContact.Partner.PartnerName);
            newContact.Partner.URLSafeName = nameHelper.CreateURLSafeName(newContact.Partner.PartnerName);
            newContact.Partner.SearchString = search;

            if (CheckForRequiredFields(newContact))
            {
                if (CheckForDuplicateKeys(newContact))
                {
                    var contactList = new List<Contact> { newContact };
                    newContact.Partner.Contacts = contactList;
                    partnerRepository.Update(newContact.Partner);
                    partnerRepository.SaveChanges();
                    return RedirectToAction("Details", new { id = nameHelper.CreateURLSafeName(newContact.Partner.PartnerName) });
                }
            }            

            return View(newContact);
        }

        [Authorize(Roles = "Read-Only User, Privileged User, Admin")]
        public ActionResult Export(string id)
        {
            ExcelExport export = new ExcelExport();
            var homeModel = new HomeModel();
            var homeModels = new List<HomeModel>();      
            homeModel.Partner = partnerRepository.GetSinglePartnerByName(id);
            homeModel.CampusUnits = campusUnitRepository.FindCampusUnitsForPartner(homeModel.Partner);
            homeModels.Add(homeModel);

            string csvFileString = export.ExportPartnersContactsCampusUnitData(homeModels);

            return File(new UTF8Encoding().GetBytes(csvFileString), "text/csv", "ExcelExport.csv");
        }

        [Authorize(Roles = "Privileged User, Admin")]
        public ActionResult Edit(string id, string search)
        {
            var partner = partnerRepository.GetSinglePartnerByName(id);
            partner.SearchString = search;
            partner.URLSafeName = id;
            return View(partner);
        }

        [HttpPost]
        [Authorize(Roles = "Privileged User, Admin")]
        public ActionResult Edit(Partner editPartner, string search)
        {
            editPartner.SearchString = search;
            if (ModelState.IsValid)
            {
                using (var context = new CPTSContext())
                {
                    context.Entry(editPartner).State = EntityState.Modified;
                    context.SaveChanges();
                }
                return RedirectToAction("Details", new { id = nameHelper.CreateURLSafeName(editPartner.PartnerName) });
            }
            return View(editPartner);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(string id)
        {
            var partner = partnerRepository.GetSinglePartnerByName(id);
            partner.URLSafeName = id;
            return View(partner);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(string id)
        {
            var partner = partnerRepository.GetSinglePartnerByName(id);
            partner.URLSafeName = id;
            if (contactRepository.FindContactsFromPartnerName(partner.PartnerName).Count != 0)
            {
                ViewBag.Message = "Must delete all Contacts before deleting " + partner.PartnerName;
                return View(partner);
            }
            partnerRepository.Remove(partner);
            partnerRepository.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "Privileged User, Admin")]
        public ActionResult AddTag(string id, string search)
        {
            var partner = partnerRepository.GetSinglePartnerByName(id);
            var editPartner = new AddTagsPartner { Partner = partner };
            editPartner.SearchString = search;
            editPartner.SelectedTag = "";   //Supply an empty value for selected tag name, so that the view doesn't complain
            editPartner.Tags = tagRepository.GetAllTagNames();
            var tagObjects = tagRepository.FindTagsFromPartnerName(partner.PartnerName);
            editPartner.Partner.SearchTags = tagObjects;
            List<string> tagNames = new List<string>();
            foreach(var tag in tagObjects)
            {
                tagNames.Add(tag.TagName);      //Convert collected list of tags to tagNames
            }
            foreach(var item in tagNames)
            {
                editPartner.Tags.Remove(item);  //Trim results from 'GetAllTagNames' by removing tagNames Associated with the partner
            }

            return View(editPartner);
        }

        [HttpPost]
        [Authorize(Roles = "Privileged User, Admin")]
        public ActionResult AddTag(AddTagsPartner addedTagPartner)
        {
            if (addedTagPartner.SelectedTag != null)
            {
                using (var context = new CPTSContext())
                {
                    var updatedPartner = context.Partners.Find(addedTagPartner.Partner.PartnerName);    //Get the partner
                    var newTag = context.Tags.Find(addedTagPartner.SelectedTag);
                    //"Rebuild" UpdatedPartner Prior to saving it
                    updatedPartner.Activities = context.Activities.Where(a => a.Partner.PartnerName == updatedPartner.PartnerName).ToList();
                    updatedPartner.Contacts = context.Contacts.Where(c => c.Partner.PartnerName == updatedPartner.PartnerName).ToList();
                    updatedPartner.SearchString = addedTagPartner.SearchString;
                    updatedPartner.SearchTags = new List<Tag>();
                    updatedPartner.URLSafeName = nameHelper.CreateURLSafeName(updatedPartner.PartnerName);
                    updatedPartner.SearchTags.Add(newTag);
                    context.Entry(updatedPartner).State = EntityState.Modified; // Update the Contact
                    context.SaveChanges();
                }
            }

            return RedirectToAction("Details", new { id = addedTagPartner.Partner.PartnerName, search = addedTagPartner.SearchString});
        }
        

        private bool CheckForRequiredFields(Contact newContact)
        {
            if (newContact.Email != null && newContact.Partner.PartnerName != null)
            {
                return true;
            }

CPTS/CPTS/Views/Partner/AddTag.cshtml
@model CPTS.Models.AddTagsPartner


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Add Tag to Community Partner</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Partner.PartnerName)
        @Html.HiddenFor(model => model.SearchString)

        <div class="form-group">
            @Html.Label("Add Tag", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-lg-10">
                @Html.DropDownListFor(model => model.SelectedTag, new SelectList(Model.Tags), new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancel", "Details", "Partner", new { id = Model.Partner.PartnerName, search = Model.SearchString }, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CPTS/CPTS/Views/Partner/CreateContact.cshtml
@model CPTS.Repository.Models.Contact

@if (ViewBag.Message != null)
{
    <h4 style="color: red">
        @Html.Raw(ViewBag.Message)
    </h4>
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Add Contact</h4>
        <hr />
        
        @Html.HiddenFor(model => model.Partner.PartnerName)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.Label("Community Partner", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Partner.PartnerName, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.Partner.PartnerName, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.Label("Contact Email*", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("First Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Phone Number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Notes, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Partner", "Details", new {id=Model.Partner.URLSafeName, search = Model.Partner.SearchString}, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CPTS/CPTS/Views/Partner/Delete.cshtml
@model CPTS.Repository.Models.Partner

@if (ViewBag.Message != null)
{
    <h4 style="color: red">
        @Html.Raw(ViewBag.Message)
    </h4>
}
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Delete Community Partner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Community Partner
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PartnerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-warning" />
        </div>
    }
    @Html.ActionLink("Back to Partner", "Details", "Partner", new { id = Model.URLSafeName }, new { @class = "btn btn-default" })
</div>

CPTS/CPTS/Views/Partner/Details.cshtml
@model CPTS.Repository.Models.Partner

<div>
    <h4>Community Partner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Name
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PartnerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>
        <dd>
            <a href="http://@Model.Website">@Model.Website</a>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            Campus Units
        </dt>
        <dd>
            @Html.DisplayFor(model => model.campusUnitString)
        </dd>

        <dt>
            Tags
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tagString)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd>
            @Html.TextAreaFor(model => model.Notes, new { @class = "form-control", @readonly="readonly"})
        </dd>
    </dl>
</div>

<p></p>
<div>
    <p></p>
    @if (User.IsInRole("Privileged User") || User.IsInRole("Admin"))
    {
        @Html.ActionLink("Add Contact", "CreateContact", "Partner", new { id = Model.URLSafeName, search = Model.SearchString }, new { @class = "btn btn-default" })

        @Html.ActionLink("Edit Partner", "Edit", "Partner", new { id = Model.URLSafeName, search = Model.SearchString }, new { @class = "btn btn-default" })
    }

    @if (User.IsInRole("Admin"))
    {
        @Html.ActionLink("Delete Partner", "Delete", "Partner", new { id = Model.URLSafeName }, new { @class = "btn btn-default" })
    }
    @Html.ActionLink("Export to Excel", "Export", "Partner", new { id = Model.URLSafeName }, new { @class = "btn btn-default" })
</div>
<hr />

<h4>Community Partner's Contacts - @Html.Raw(ViewBag.Message)</h4>
<table class="table">
    <tr>
        <th>
            First Name
        </th>
        <th>
            Last Name
        </th>
        <th>
            Email
        </th>
        <th>
            Phone Number
        </th>
        <th>
            Title
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Contacts)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>              
            <td>
                @Html.ActionLink("Details", "Details", "Contact", new { id = item.URLSafeEmail, search = Model.SearchString }, null) 
            </td>
        </tr>
    }
</table>
<hr />

<h4>Community Partner's Activities - @Html.Raw(Model.Activities.Count)</h4>
<table class="table">
    <tr>
        <th>
            Activity Subject
        </th>
        <th>
            Activity Date
        </th>
        <th>
            Activity Campus Unit
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model.Activities)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Subject)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CampusUnit.Name)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", "Activity", new { id = item.URLSafeSubject, date = item.Date, partnerName = Model.URLSafeName }, null)
            </td>
        </tr>
    }
</table>

CPTS/CPTS/Views/Partner/Edit.cshtml
@model CPTS.Repository.Models.Partner

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edit Community Partner</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PartnerName)

        <div class="form-group">
            @Html.Label("Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PartnerName, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.PartnerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Notes, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancel", "Details", "Partner", new { id = Model.URLSafeName, search = Model.SearchString }, new { @class = "btn btn-default" })
    @if (User.IsInRole("Privileged User") || User.IsInRole("Admin"))
    {
        @Html.ActionLink("Add Tag", "AddTag", "Partner", new { id = Model.PartnerName, search = Model.SearchString }, new { @class = "btn btn-default" })
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}