CPTS/CPTS/Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CPTS.Helpers;
using CPTS.Models;
using CPTS.Repository.Context;
using CPTS.Repository.Models;
using CPTS.Repository.Helpers;

namespace CPTS.Controllers
{
    [Authorize(Roles = "Read-Only User, Privileged User, Admin")]
    public class ActivityController : Controller
    {

        ActivityRepository activityRepository = new ActivityRepository();
        PartnerRepository partnerRepository = new PartnerRepository();
        CampusUnitRepository campusUnitRepository = new CampusUnitRepository();
        ContactRepository contactRepository = new ContactRepository();
        SafeURL URLHelper = new SafeURL();
        // GET: Activity
        public ActionResult Details(string id, DateTime date, string partnerName = "", string email = "")
        {
            var activity = activityRepository.FindActivityUsingSubjectContactDateAndPartner(id, date, URLHelper.CreateNameFromSafeName(partnerName), URLHelper.CreateEmailFromSafeEmail(email));
            activity.Partner = partnerRepository.GetPartnerByActivity(activity);
            activity.CampusUnit = campusUnitRepository.GetCampusUnitFromActivity(activity);
            activity.Contacts = contactRepository.FindContactsByActivity(activity);
            foreach (var contact in activity.Contacts) contact.URLSafeEmail = URLHelper.CreateURLSafeEmail(contact.Email);
            activity.ContactEmail = URLHelper.CreateURLSafeEmail(activity.Contacts.FirstOrDefault().Email);
            activity.URLSafeSubject = id;
            ViewBag.ContactCount = activity.Contacts.Count;

            return View(activity);
        }


        [Authorize(Roles = "Privileged User, Admin")]
        public ActionResult AddContacts(string id, string email)
        {
            var activity = activityRepository.FindSingleActivityFromSubject(id);
            activity.URLSafeSubject = id;
            var editActivity = new AddContactsActivity {Activity = activity};
            var partner = partnerRepository.GetPartnerByActivity(activity);
            editActivity.PartnerName = partner.PartnerName;
            editActivity.Activity.Partner = partner;
            editActivity.Contacts = contactRepository.ReturnAllContactsEmails();
            var contacts = contactRepository.FindContactsByActivity(activity);
            foreach (var contact in contacts)
            {
                editActivity.Contacts.Remove(contact.Email); // remove the Activity's Contacts from the list  
            }
            editActivity.ContactEmail = email;
            return View(editActivity);
        }

        [HttpPost]
        [Authorize(Roles = "Privileged User, Admin")]
        public ActionResult AddContacts(AddContactsActivity editActivity)
        {
            using (var context = new CPTSContext())
            {
                string subject = editActivity.Activity.URLSafeSubject.Replace(ConstantsChars.ReplacementCharForForwardSlash, '/');
                subject = subject.Replace(ConstantsChars.ReplacementCharForColon, ':');
                subject = subject.Replace(ConstantsChars.ReplacementCharForPeriod, '.');
                var updatedActivity = context.Activities.First(a => a.Subject == subject && a.Partner.PartnerName == editActivity.PartnerName && a.Date == editActivity.Activity.Date); // find the Activity
                updatedActivity.Partner = context.Partners.Find(editActivity.PartnerName); // find the Partner
                updatedActivity.Contacts = new List<Contact> { context.Contacts.Find(editActivity.ContactEmail) }; // create a list of Contacts with the new Contact
                updatedActivity.CampusUnit =
                    context.CampusUnits.First(c => c.Activities.Any(a => a.Subject == updatedActivity.Subject
                                                                         &&
                                                                         DbFunctions.TruncateTime(a.Date) ==
                                                                         DbFunctions.TruncateTime(updatedActivity.Date)
                                                                         &&
                                                                         a.Partner.PartnerName ==
                                                                         updatedActivity.Partner.PartnerName)); // find the CampusUnit
                var editContact = context.Contacts.Find(editActivity.ContactEmail); // find the new Contact to be added to the Activity
                context.Entry(editContact).State = EntityState.Modified; // Update the Contact
                context.SaveChanges();
                editActivity.ContactEmail = editActivity.ContactEmail.Replace('.', ConstantsChars.ReplacementCharForPeriod);
            }
            return RedirectToAction("Details", new { id = editActivity.Activity.URLSafeSubject, date = editActivity.Activity.Date, email = editActivity.ContactEmail });
        }


        [Authorize(Roles = "Privileged User, Admin")]
        public ActionResult ActivityEdit(string id, string email)
        {
            var activity = activityRepository.FindSingleActivityFromSubject(id);
            activity.Partner = partnerRepository.GetPartnerByActivity(activity);
            activity.CampusUnit = campusUnitRepository.GetCampusUnitFromActivity(activity);
            activity.Contacts = contactRepository.FindContactsByActivity(activity);
            activity.ContactEmail = email;
            activity.URLSafeSubject = id;

            if (activity.Notes == null)
            {
                activity.Notes = "";
            }

            return View(activity);
        }

        [HttpPost]
        [Authorize(Roles = "Privileged User, Admin")]
        public ActionResult ActivityEdit(Activity editActivity)//, string Subject)
        {
            editActivity.URLSafeSubject = editActivity.Subject.Replace('/', ConstantsChars.ReplacementCharForForwardSlash);     //Construct URL Safe Email
            editActivity.URLSafeSubject = editActivity.URLSafeSubject.Replace(':', ConstantsChars.ReplacementCharForColon);
            editActivity.URLSafeSubject = editActivity.URLSafeSubject.Replace('.', ConstantsChars.ReplacementCharForPeriod);

            editActivity.Date = activityRepository.GetDateByActivitySubject(editActivity.URLSafeSubject);
            editActivity.Partner = partnerRepository.GetPartnerByActivity(editActivity);
            editActivity.Partner = partnerRepository.GetSinglePartnerByName(editActivity.Partner.PartnerName);
            editActivity.CampusUnit = campusUnitRepository.GetCampusUnitFromActivity(editActivity);
            editActivity.Contacts = contactRepository.FindContactsByActivity(editActivity);

            //The hiccup comes when the validation is called and it doesn't appreciate the partner field
            //if (ModelState.IsValid)
            //{
                using (var context = new CPTSContext())
                {
                    context.Entry(editActivity).State = EntityState.Modified;
                    context.SaveChanges();
                }
                return RedirectToAction("Details", new { id = editActivity.Subject, date = editActivity.Date, email = editActivity.ContactEmail });
            //}
            //return View(editActivity);
        }
    }
}

CPTS/CPTS/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CPTS.Helpers;
using CPTS.Models;
using CPTS.Repository.Context;
using CPTS.Repository.Models;
using CPTS.Repository.Helpers;

namespace CPTS.Controllers
{
    [Authorize(Roles = "Read-Only User, Privileged User, Admin")]
    public class ContactController : Controller
    {
        ContactRepository contactRepository = new ContactRepository();
        ActivityRepository activityRepository = new ActivityRepository();
        CampusUnitRepository campusUnitRepository = new CampusUnitRepository();
        CampusUnitDataRepository campusUnitDataRepository = new CampusUnitDataRepository();
        PartnerRepository partnerRepository = new PartnerRepository();
        SafeURL nameHelper = new SafeURL();

        public ActionResult Details(string id, string search)
        {
            var contact = contactRepository.GetSingleContactByEmail(id);
            contact.URLSafeEmail = id;
            contact.Activities = activityRepository.FindActivitiesFromContactEmail(contact.Email);
            contact.CampusUnitData = campusUnitDataRepository.FindCampusUnitDataFromContactEmail(contact.Email);
            contact.Partner = partnerRepository.GetPartnerByContactEmail(contact.Email);
            contact.Partner.URLSafeName = nameHelper.CreateURLSafeName(contact.Partner.PartnerName);
            if (search == null)
            {
                contact.Partner.SearchString = "" + ConstantsChars.CharForStringSeperator
                    + ConstantsChars.CharForStringSeperator + ConstantsChars.CharForStringSeperator;
            }
            else contact.Partner.SearchString = search;

            foreach (var activity in contact.Activities)    
            {
                activity.CampusUnit = campusUnitRepository.GetCampusUnitFromActivityNonTruncateTime(activity);
                activity.URLSafeSubject = nameHelper.CreateUrlSafeSubject(activity.Subject);
            }
            foreach (var campusUnitData in contact.CampusUnitData)
            {
                campusUnitData.AssignedContact = contact;
                campusUnitData.CampusUnit = campusUnitRepository.GetCampusUnitForCampusUnitData(campusUnitData);
            }
            ViewBag.Message = contact.Activities.Count;
            return View(contact);
        }

        [Authorize(Roles = "Privileged User, Admin")]
        public ActionResult CreateActivity(string id)
        {
            var contact = new List<Contact> {contactRepository.GetSingleContactByEmail(id)};
            contact.First().URLSafeEmail = contact.First().Email.Replace('.', ConstantsChars.ReplacementCharForPeriod);
            var createActivity = new CreateActivity();
            var activity = new Activity();
            activity.ContactEmail = id.Replace(ConstantsChars.ReplacementCharForPeriod, '.');
            activity.Contacts = contact;
            var date = DateTime.Now;
            activity.Date = new DateTime(date.Year, date.Month, date.Day, date.Hour, date.Minute, date.Second, date.Kind); // remove milliseconds
            createActivity.Activity = activity;
            createActivity.CampusUnitNames = campusUnitRepository.GetAllCampusUnitsNames();
            return View(createActivity);
        }

        [HttpPost]
        [Authorize(Roles = "Privileged User, Admin")]
        public ActionResult CreateActivity(CreateActivity newActivity)
        {
            newActivity.Activity.Subject = KeyTrimmer.TrimTrailingSpaces(newActivity.Activity.Subject); //These two line remove any trailing whitespace from subject
            newActivity.Activity.URLSafeSubject = KeyTrimmer.TrimTrailingSpaces(newActivity.Activity.URLSafeSubject);

            if (CheckForRequiredFields(newActivity))
            {
                if (CheckForDuplicateKeysActivityCreate(newActivity))
                {
                    using (var context = new CPTSContext())
                    {
                        newActivity.Activity.Partner =
                            context.Partners.FirstOrDefault(
                                p => p.Contacts.Any(c => c.Email == newActivity.Activity.ContactEmail));
                        // find the Partner of the Contact and add it

                        newActivity.Activity.Contacts = new List<Contact>
                        {
                            context.Contacts.Find(newActivity.Activity.ContactEmail)
                        };
                        // find the Contact and make a list and add it

                        newActivity.Activity.CampusUnit = context.CampusUnits.Find(newActivity.CampusUnitName);

                        context.Activities.Add(newActivity.Activity);
                        context.SaveChanges();
                    }
                    return RedirectToAction("Details", new { id = newActivity.Activity.ContactEmail.Replace('.', ConstantsChars.ReplacementCharForPeriod) });
                }
            }

            newActivity.CampusUnitNames = campusUnitRepository.GetAllCampusUnitsNames();
            newActivity.Activity.Contacts = new List<Contact> { contactRepository.GetSingleContactByEmail(newActivity.Activity.ContactEmail) };
            newActivity.Activity.Contacts.First().URLSafeEmail = newActivity.Activity.Contacts.First().Email.Replace('.', ConstantsChars.ReplacementCharForPeriod);
            return View(newActivity);

        }

        [Authorize(Roles = "Privileged User, Admin")]
        public ActionResult Edit(string id)
        {
            var contact = contactRepository.GetSingleContactByEmail(id);
            contact.URLSafeEmail = contact.Email.Replace('.', ConstantsChars.ReplacementCharForPeriod);
            return View(contact);
        }

        [HttpPost]
        [Authorize(Roles = "Privileged User, Admin")]
        public ActionResult Edit(Contact editContact)
        {
            if (ModelState.IsValid)
            {
                using (var context = new CPTSContext())
                {
                    context.Entry(editContact).State = EntityState.Modified;
                    context.SaveChanges();
                }
                return RedirectToAction("Details", new { id = editContact.Email.Replace('.', ConstantsChars.ReplacementCharForPeriod) });
            }
            return View(editContact);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(string id)
        {
            var contact = contactRepository.GetSingleContactByEmail(id);
            contact.URLSafeEmail = id;
            return View(contact);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(string id)
        {
            string partnerName;
            using (var context = new CPTSContext())
            {
                var contact = context.Contacts.Find(id.Replace(ConstantsChars.ReplacementCharForPeriod, '.'));
                var partner = context.Partners.First(p => p.Contacts.Any(c => c.Email == contact.Email));
                partnerName = partner.PartnerName;
                context.Contacts.Remove(contact);
                context.SaveChanges();
            }
            return RedirectToAction("Details", "Partner", new { id = partnerName });
        }

        [Authorize(Roles = "Privileged User, Admin")]
        public ActionResult CreateCampusUnitData(string id)
        {
            CreateCampusUnitData createCampusUnitData = new CreateCampusUnitData();
            var contact = new List<Contact> { contactRepository.GetSingleContactByEmail(id) };
            contact.First().URLSafeEmail = contact.First().Email.Replace('.', ConstantsChars.ReplacementCharForPeriod);
            CampusUnitData campusUnitData = new CampusUnitData();
            var campusUnit = new CampusUnit();
            campusUnitData.CampusUnit = campusUnit;
            campusUnitData.CampusUnit.Name = "";
            campusUnitData.AssignedContact = contact.ElementAt(0);
            campusUnitData.AssignedContact.Email = id.Replace(ConstantsChars.ReplacementCharForPeriod, '.');
            createCampusUnitData.CampusUnitData = campusUnitData;
            createCampusUnitData.Semesters = GetSemesters();
            createCampusUnitData.CampusUnits = GetCampusUnitNames(campusUnitData.AssignedContact.Email); //Add a list of campus unit names for the user to select from

            return View(createCampusUnitData);
        }

        [HttpPost]
        [Authorize(Roles = "Privileged User, Admin")]
        public ActionResult CreateCampusUnitData(CreateCampusUnitData newCampusUnitData)
        {
            if (CheckForRequiredFieldsCampusUnitDataCreate(newCampusUnitData))
            {
                if (CheckForDuplicateKeyCampusUnitDataCreate(newCampusUnitData))
                {
                    using (var context = new CPTSContext())
                    {
                        newCampusUnitData.CampusUnitData.AssignedContact = context.Contacts.Find(newCampusUnitData.CampusUnitData.AssignedContact.Email);
                        context.Entry(newCampusUnitData.CampusUnitData.CampusUnit).State = EntityState.Unchanged;
                        context.CampusUnitDataRecords.Add(newCampusUnitData.CampusUnitData);
                        context.SaveChanges();
                    }
                    return RedirectToAction("Details", new { id = newCampusUnitData.CampusUnitData.AssignedContact.Email.Replace('.', ConstantsChars.ReplacementCharForPeriod) });
                }               
            }
            var contact =  contactRepository.GetSingleContactByEmail(newCampusUnitData.CampusUnitData.AssignedContact.Email);

CPTS/CPTS/Views/Activity/ActivityEdit.cshtml
@model CPTS.Repository.Models.Activity


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edit Activity</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Subject)
        @Html.HiddenFor(model => model.ContactEmail)

        <div class="form-group">
            @Html.Label("Activity Subject", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Activity Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Campus Unit", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CampusUnit.Name, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Community Partner", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Partner.PartnerName, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Activity Notes", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Notes, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancel", "Details", "Activity", new { id = Model.Subject, date = Model.Date, Model.Partner.PartnerName }, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CPTS/CPTS/Views/Activity/AddContacts.cshtml
@model CPTS.Models.AddContactsActivity


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Add Existing Contact to Activity</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Activity.Subject)

        @Html.HiddenFor(model => model.Activity.Date)
        
        @Html.HiddenFor(model => model.PartnerName)
        
        @Html.HiddenFor(model => model.Activity.URLSafeSubject)

        <div class="form-group">
            @Html.Label("Activity Subject", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-lg-10">
                @Html.EditorFor(model => model.Activity.Subject, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Activity Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-lg-10">
                @Html.EditorFor(model => model.Activity.Date, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Contact Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-lg-10">
                @Html.DropDownListFor(model => model.ContactEmail, new SelectList(Model.Contacts), new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancel", "Details", "Activity", new { id = Model.Activity.Subject, date = Model.Activity.Date, Model.Activity.Partner.PartnerName }, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CPTS/CPTS/Views/Activity/Details.cshtml
@model CPTS.Repository.Models.Activity

<div>
    <h4>Activity</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Activity Subject
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>
        <dt>
            Activity Date
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            Campus Unit
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CampusUnit.Name)
        </dd>
        <dt>
            Community Partner
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Partner.PartnerName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd>
            @Html.TextAreaFor(model => model.Notes, new { @class = "form-control", @readonly = "readonly" })
        </dd>
    </dl>
</div>
<p>
</p>
@if (User.IsInRole("Privileged User") || User.IsInRole("Admin"))
{
    @Html.ActionLink("Add Contact", "AddContacts", "Activity", new { id = Model.URLSafeSubject, email = Model.ContactEmail }, new { @class = "btn btn-default" })

    @Html.ActionLink("Edit Activity", "ActivityEdit", "Activity", new { id = Model.URLSafeSubject, email = Model.ContactEmail }, new { @class = "btn btn-default" })
}
@Html.ActionLink("Back to Contact", "Details", "Contact", new { id = Model.ContactEmail }, new { @class = "btn btn-default" })
<hr />

<h4>Activity's Contacts - @Html.Raw(ViewBag.ContactCount)</h4>
<table class="table">
    <tr>
        <th>
            First Name
        </th>
        <th>
            Last Name
        </th>
        <th>
            Email
        </th>
        <th>
            Phone Number
        </th>
        <th>
            Title
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Contacts)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>                    
            <td>
                @Html.ActionLink("Details", "Details", "Contact", new { id = item.URLSafeEmail }, null)
            </td>
        </tr>
    }
</table>