CPTS/CPTS/Controllers/ActivitySearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CPTS.Repository.Models;
using CPTS.Helpers;
using CPTS.Repository.Context;
using System.Text;
using CPTS.Repository.Helpers;

namespace CPTS.Controllers
{
    [Authorize(Roles = "Read-Only User, Privileged User, Admin")]
    public class ActivitySearchController : Controller
    {
        ActivityRepository activityRepository = new ActivityRepository();
        PartnerRepository partnerRepository = new PartnerRepository();
        CampusUnitRepository campusUnitRepository = new CampusUnitRepository();
        ContactRepository contactRepository = new ContactRepository();
        SafeURL activityHelper = new SafeURL();

        [Authorize(Roles = "Read-Only User, Privileged User, Admin")]
        public ActionResult ActivitySearch(string searchActivitySubject, string searchDateFrom, string searchDateTo)
        {
            var activityList = activityRepository.FindActivitiesBasedOnSubjectAndDate(searchActivitySubject, searchDateFrom, searchDateTo);
            foreach (var activity in activityList)
            {
                activity.URLSafeSubject = activityHelper.CreateUrlSafeSubject(activity.Subject);
                activity.Partner = partnerRepository.GetPartnerByActivity(activity);
                activity.CampusUnit = campusUnitRepository.GetCampusUnitFromActivityNonTruncateTime(activity);
                activity.SearchString = searchActivitySubject + ConstantsChars.CharForStringSeperator + searchDateFrom 
                    + ConstantsChars.CharForStringSeperator + searchDateTo;
            }
            ViewBag.Message = activityList.Count;

            return View(activityList);
        }

        [Authorize(Roles = "Read-Only User, Privileged User, Admin")]
        public ActionResult ExportActivities(string searchString)
        {       
            string csvFileString = "No search results to export.";

            if (searchString != null)
            {
                ExcelExport export = new ExcelExport();
                string[] searchStringArray = searchString.Split(ConstantsChars.CharForStringSeperator);

                List<Activity> activityList = activityRepository.FindActivitiesBasedOnSubjectAndDate(searchStringArray[0], searchStringArray[1], searchStringArray[2]);

                foreach (var activity in activityList)
                {
                    activity.URLSafeSubject = activityHelper.CreateUrlSafeSubject(activity.Subject);
                    activity.Partner = partnerRepository.GetPartnerByActivity(activity);
                    activity.CampusUnit = campusUnitRepository.GetCampusUnitFromActivityNonTruncateTime(activity);
                    activity.Contacts = contactRepository.FindContactsByActivity(activity);
                }
                csvFileString = export.ExportActivities(activityList);
            }

            return File(new UTF8Encoding().GetBytes(csvFileString), "text/csv", "ExcelExportActivities.csv");
        }
    }
}

CPTS/CPTS/Controllers/ContactSearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CPTS.Helpers;
using CPTS.Repository.Context;
using CPTS.Repository.Models;
using System.Text;
using CPTS.Repository.Helpers;

namespace CPTS.Controllers
{
    [Authorize(Roles = "Read-Only User, Privileged User, Admin")]
    public class ContactSearchController : Controller
    {
        ContactRepository contactRepository = new ContactRepository();
        PartnerRepository partnerRepository = new PartnerRepository();
        ActivityRepository activityRepository = new ActivityRepository();
        CampusUnitDataRepository campusUnitDataRepository = new CampusUnitDataRepository();
        CampusUnitRepository campusUnitRepository = new CampusUnitRepository();

        SafeURL emailHelper = new SafeURL();
        [Authorize(Roles = "Read-Only User, Privileged User, Admin")]
        public ActionResult ContactSearch(string searchContactName, string searchContactEmail, string searchPartnerName)
        {
            var contactList = contactRepository.FindContactsBasedOnNameEmailAndPartnerName(searchContactName, searchContactEmail, searchPartnerName);
            foreach (var contact in contactList)
            {
                contact.URLSafeEmail = emailHelper.CreateURLSafeEmail(contact.Email);
                contact.Partner = partnerRepository.GetPartnerByContactEmail(contact.Email);
                contact.SearchString = searchContactName + ConstantsChars.CharForStringSeperator + searchContactEmail
                    + ConstantsChars.CharForStringSeperator + searchPartnerName;
            }
            ViewBag.Message = contactList.Count;

            return View(contactList);
        }

        [Authorize(Roles = "Read-Only User, Privileged User, Admin")]
        public ActionResult ExportContacts(string searchString)
        {
            string csvFileString = Export(searchString, false);

            return File(new UTF8Encoding().GetBytes(csvFileString), "text/csv", "ExcelExportContacts.csv");
        }

        [Authorize(Roles = "Read-Only User, Privileged User, Admin")]
        public ActionResult ExportContactsCampusUnitData(string searchString)
        {
            string csvFileString = Export(searchString, true);

            return File(new UTF8Encoding().GetBytes(csvFileString), "text/csv", "ExcelExportContactsCampusUnitData.csv");
        }

        public string Export(string searchString, bool campusUnitData)
        {
            string csvFileString = "No search results to export.";

            if (searchString != null)
            {
                ExcelExport export = new ExcelExport();
                string[] searchStringArray = searchString.Split(ConstantsChars.CharForStringSeperator);

                List<Contact> contactList = contactRepository.FindContactsBasedOnNameEmailAndPartnerName(searchStringArray[0], searchStringArray[1], searchStringArray[2]);

                foreach (var contact in contactList)
                {
                    contact.Partner = partnerRepository.GetPartnerByContactEmail(contact.Email);
                    contact.Activities = activityRepository.FindActivitiesFromContactEmail(contact.Email);
                    contact.CampusUnitData = campusUnitDataRepository.FindCampusUnitDataFromContactEmail(contact.Email);

                    foreach (var data in contact.CampusUnitData)
                    {
                        data.AssignedContact = contactRepository.GetSingleContactByEmail(contact.Email);
                        data.CampusUnit = campusUnitRepository.GetCampusUnitForCampusUnitData(data);
                    }
                }
                if (campusUnitData) csvFileString = export.ExportContactsCampusUnitData(contactList);
                else csvFileString = export.ExportContacts(contactList);
            }

            return csvFileString;
        }
    }
}

CPTS/CPTS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Compass</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")"> <img src="@Url.Content("~/CompassLogo.png")" class="navbar-brand"/></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Community Partners", "Index", "Home")</li>
                    <li>@Html.ActionLink("Contacts", "ContactSearch", "ContactSearch")</li>
                    <li>@Html.ActionLink("Activities", "ActivitySearch", "ActivitySearch")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="color: #FFFFFF">
            @Html.ActionLink("About", "About", "Home", null, new { @style = "color: #FFFFFF" })
            <p>&copy; @DateTime.Now.Year - COMPASS </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>